#pragma once


#include <string>
#include "Contra_ANI_ID.h"
#include "debug.h"
#include "Enemies_ID.h"
using namespace std;
enum Action {
    ACT_IDLE_RIGHT,
    ACT_IDLE_LEFT,
    ACT_LOOK_UP_RIGHT,
    ACT_LOOK_UP_LEFT,
    ACT_LOOK_DOWN_RIGHT,
    ACT_LOOK_DOWN_LEFT,
    ACT_LYING_RIGHT,
    ACT_LYING_LEFT,
    ACT_WALK_RIGHT,
    ACT_SHOOT_WALK_RIGHT,
    ACT_WALK_LEFT,
    ACT_SHOOT_WALK_LEFT,
    ACT_WALK_RIGHT_LOOK_UP,
    ACT_WALK_LEFT_LOOK_UP,
    ACT_WALK_RIGHT_LOOK_DOWN,
    ACT_WALK_LEFT_LOOK_DOWN,
    ACT_SWIM_RIGHT,
    ACT_SWIM_LEFT,
    ACT_SWIM_SHOOT_RIGHT,
    ACT_SWIM_SHOOT_LEFT,
    ACT_SWIM_LOOK_UP_STAND_LEFT,
    ACT_SWIM_LOOK_UP_STAND_RIGHT,
    ACT_SWIM_RIGHT_LOOK_UP,
    ACT_SWIM_LEFT_LOOK_UP,
    ACT_DIVE,
    ACT_JUMP_RIGHT,
    ACT_JUMP_LEFT,
    ACT_FALL_RIGHT,
    ACT_FALL_LEFT,
    ACT_DIE_RIGHT,
    ACT_DIE_LEFT,
    ACT_DIE_JUMPING_RIGHT,
    ACT_DIE_JUMPING_LEFT,
    // for Turret
    ACT_ANGLE_1_OCLOCK,
    ACT_ANGLE_2_OCLOCK,
    ACT_ANGLE_3_OCLOCK,
    ACT_ANGLE_4_OCLOCK,
    ACT_ANGLE_5_OCLOCK,
    ACT_ANGLE_6_OCLOCK,
    ACT_ANGLE_7_OCLOCK,
    ACT_ANGLE_8_OCLOCK,
    ACT_ANGLE_9_OCLOCK,
    ACT_ANGLE_10_OCLOCK,
    ACT_ANGLE_11_OCLOCK,
    ACT_ANGLE_12_OCLOCK,
    // for special object
    ACT_STANDBY_LEFT,
    ACT_STANDBY_RIGHT,
    ACT_ACTIVE_LEFT,
    ACT_ACTIVE_RIGHT,
    ACT_EMERGE_LEFT,
    ACT_EMERGE_RIGHT,
    ACT_HIDE_LEFT,
    ACT_HIDE_RIGHT,
};
#define CHAR_CONTRA 10
#define CHAR_CONTRA_BASE 12

int Get_CharANI_ID(int character, int behavior);